declare module '@material-tailwind/react/Icon'
declare module '@material-tailwind/react/Button'
declare module '@material-tailwind/react/Modal'
declare module '@material-tailwind/react/ModalBody'
declare module '@material-tailwind/react/ModalFooter'